version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - mynet
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf:
      - sonarqube_data:/opt/sonarqube/data:
      - sonarqube_logs:/opt/sonarqube/logs:
      - sonarqube_extensions:/opt/sonarqube/extensions:

networks:
  mynet:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
