version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - mynet
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynet
  clair:
    image: quay.io/coreos/clair:latest
    command: -config=/config/config.yaml
    ports:
      - 6060:6060
      - 6061:6061
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: $PWD/clair_config
        target: /config
    networks:
      - mynet
    restart: on-failure
  postgres:
    image: postgres:9.6
    networks:
      - mynet
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
networks:
  mynet:
    driver: bridge
volumes:
  jenkins_home:
  zap:
