version: "3.8"

services:
  jenkins:
    build:
      dockerfile: jenkins-dockerfile
      context: .
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - mynet
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynet

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - ./docker-compose-data/postgres-data/:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_USER=clair
      - POSTGRES_DB=clair
    networks:
      - mynet

  clair:
    image: quay.io/coreos/clair:v2.0.6
    command: -config=/config/config.yaml
    #command: -log-level=debug
    ports:
      - 6060:6060
      - 6061:6061
    depends_on: 
      - postgres
    volumes:
      - ./docker-compose-data/clair-config/:/config/:ro
      - ./docker-compose-data/clair-tmp/:/tmp/:rw
    user: root
    networks:
      - mynet

  clairctl:
    image: jgsqware/clairctl:latest
    restart: unless-stopped
    environment: 
      - DOCKER_API_VERSION=1.40
    volumes:
      - ./docker-compose-data/clairctl-reports/:/reports
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - clair
    networks:
      - mynet
    user: root

  zap:
    image: owasp/zap2docker-stable
    ports:
      - 8000:8000
    entrypoint: zap-x.sh -daemon -host 0.0.0.0 -port 8000 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=5364864132243598723485
    volumes:
      - zap:/zap/data

networks:
  mynet:
    driver: bridge
volumes:
  jenkins_home:
  clair-postgres:
  zap:
