version: "3.8"

services:
  jenkins:
    build:
      dockerfile: jenkins-dockerfile
      context: .
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - mynet
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynet

  clair-postgres:
    image: arminc/clair-db:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - clair-postgres:/var/lib/postgresql/data
    networks:
      - mynet

  clair:
    image: quay.io/coreos/clair:latest
    command: -config=/config/config.yaml
    ports:
      - "6060:6060"
      - "6061:6061"
    depends_on:
      - clair-postgres
    volumes:
      - ${PWD}/clairForClairScanner/config.yaml:/config/config.yaml
    networks:
      - mynet
    restart: on-failure

  clair-scanner:
    image: nordri/clair-scanner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge
volumes:
  jenkins_home:
  clair-postgres:
