version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - mynet
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
volumes:
  jenkins_home:
  zap:
